# Copyright 2026 Rigetti & Co, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""JAX-based quantum operator transformations."""

from ._apply import (
    apply_choi_to_density_matrix,
    apply_instrument_to_density_matrix,
    apply_instrument_to_state_vector,
    apply_kraus_to_density_matrix,
    apply_kraus_to_state_vector,
    apply_pauli_liouville_to_density_matrix,
    apply_superop_to_density_matrix,
    apply_unitary_to_density_matrix,
    apply_unitary_to_state_vector,
    compute_choi_observables_from_states,
    compute_kraus_observables_from_states,
    compute_pauli_liouville_observables_from_states,
    compute_superop_observables_from_states,
    estimate,
    partial_trace,
    select_outcome,
    state_vector_reduced_density_matrix,
    targeted_apply_instrument_to_density_matrix,
    targeted_apply_instrument_to_state_vector,
    targeted_apply_kraus_map,
    targeted_apply_kraus_map_trajectory,
    targeted_apply_superop,
    targeted_apply_unitary,
    targeted_apply_unitary_to_density_matrix,
)
from ._common_channels import (
    depolarizing_channel_superoperator,
    instrument_from_axis,
    instrument_from_confusion_and_transition,
    integrated_thermal_superoperator,
    bitphase_flip_operators,
    stochastic_leakage_operators,
)
from ._compose import (
    compose_choi,
    compose_instrument,
    compose_kraus_map,
    compose_pauli_liouville,
    compose_superop,
    compose_unitary,
    compose_operator,
)
from ._metrics import (
    average_fidelity_to_depolarizing_constant,
    average_fidelity_to_process_fidelity,
    classification_fidelity,
    depolarizing_constant_to_average_fidelity,
    depolarizing_constant_to_process_fidelity,
    fidelity,
    instrument_fidelity,
    non_demolition_fidelity,
    process_fidelity,
    process_fidelity_to_average_fidelity,
    process_fidelity_to_depolarizing_constant,
    stochastic_infidelity,
    unitarity,
    unitarity_to_stochastic_infidelity,
    unitary_entanglement_fidelity,
)
from ._operator_basis import (
    hermitian_weyl_basis,
    hermitian_weyl_basis_labels,
    n_qudit_basis,
    n_qudit_herm_basis,
    weyl_basis,
    weyl_basis_labels,
)
from ._observables import bitstring_probability, probabilities
from ._exponentiation import (
    power_choi,
    power_kraus,
    power_pauli_liouville,
    power_superop,
    power_unitary,
    exp,
    cis,
    evolve,
)
from ._generators import unitary_to_hamiltonian
from ._promotion import (
    embed,
    permute,
    promote,
    promote_incoherent,
    promote_state_vector_to_density_matrix,
    promote_hilbert_space,
)
from ._squeeze import squeeze
from ._quantum_objects import QuantumInstrument
from ._quantum_objects import (
    Choi,
    DensityMatrix,
    Involution,
    KrausMap,
    Lindbladian,
    Observable,
    Operator,
    PauliLiouville,
    QuantumObject,
    State,
    StateVector,
    SuperOp,
    SuperOperator,
    Unitary,
)
from ._random import (
    ginibre_matrix_complex,
    random_choi,
    random_density_matrix,
    random_state_vector,
    random_unitary,
    random_operator,
    random_observable,
)
from ._state import (
    mixed_state_matrix,
    tensor_density_matrices,
    tensor_state_vectors,
    zero_state_matrix,
    zero_state_vector,
)
from ._superoperator_transformations import (
    choi_to_kraus,
    choi_to_pauli_liouville,
    choi_to_superop,
    kraus_to_choi,
    kraus_to_pauli_liouville,
    kraus_to_superop,
    pauli_liouville_to_choi,
    pauli_liouville_to_kraus,
    pauli_liouville_to_superop,
    superop_to_choi,
    superop_to_kraus,
    superop_to_pauli_liouville,
    to_choi,
    to_kraus,
    to_pauli_liouville,
    to_superop,
    truncate_kraus,
    unitary_to_choi,
    unitary_to_kraus_map,
    unitary_to_pauli_liouville,
    unitary_to_superop,
)
from ._tensor import (
    tensor_choi,
    tensor_density_matrix,
    tensor_instrument,
    tensor_involution,
    tensor_kraus,
    tensor_observable,
    tensor_pauli_liouville,
    tensor_state_vector,
    tensor_superop,
    tensor_unitary,
    tensor_operator,
)
from ._validation import (
    validate,
    is_completely_positive,
    is_cptp,
    is_hermitian,
    is_hermicity_preserving,
    is_identity_matrix,
    is_one_design,
    is_positive_semidefinite_matrix,
    is_trace_preserving,
    is_two_design,
    is_unitary,
)
from ._visualization import plot

# Import gates, states, ensembles and lindbladians as submodules
from . import gates
from . import states
from . import ensembles
from . import lindbladians

__all__ = [
    # Apply superoperator functions
    "compute_choi_observables_from_states",
    "compute_kraus_observables_from_states",
    "compute_pauli_liouville_observables_from_states",
    "compute_superop_observables_from_states",
    "estimate",
    "partial_trace",
    "apply_choi_to_density_matrix",
    "apply_kraus_to_density_matrix",
    "apply_pauli_liouville_to_density_matrix",
    "apply_superop_to_density_matrix",
    "apply_unitary_to_density_matrix",
    "apply_unitary_to_state_vector",
    "apply_kraus_to_state_vector",
    "apply_instrument_to_density_matrix",
    "apply_instrument_to_state_vector",
    "select_outcome",
    "state_vector_reduced_density_matrix",
    "targeted_apply_instrument_to_density_matrix",
    "targeted_apply_instrument_to_state_vector",
    "targeted_apply_kraus_map",
    "targeted_apply_kraus_map_trajectory",
    "targeted_apply_superop",
    "targeted_apply_unitary",
    "targeted_apply_unitary_to_density_matrix",
    # Common channels
    "depolarizing_channel_superoperator",
    "integrated_thermal_superoperator",
    "bitphase_flip_operators",
    "stochastic_leakage_operators",
    "instrument_from_confusion_and_transition",
    "instrument_from_axis",
    # Compose quantum objects
    "compose_kraus_map",
    "compose_choi",
    "compose_pauli_liouville",
    "compose_superop",
    "compose_unitary",
    "compose_instrument",
    "compose_operator",
    # Tensor quantum objects
    "tensor_kraus",
    "tensor_choi",
    "tensor_pauli_liouville",
    "tensor_superop",
    "tensor_unitary",
    "tensor_observable",
    "tensor_involution",
    "tensor_instrument",
    "tensor_operator",
    "tensor_state_vector",
    "tensor_density_matrix",
    # Superoperator transformations
    "choi_to_kraus",
    "choi_to_pauli_liouville",
    "choi_to_superop",
    "kraus_to_choi",
    "kraus_to_pauli_liouville",
    "kraus_to_superop",
    "pauli_liouville_to_choi",
    "pauli_liouville_to_kraus",
    "pauli_liouville_to_superop",
    "superop_to_choi",
    "superop_to_kraus",
    "superop_to_pauli_liouville",
    "to_choi",
    "to_pauli_liouville",
    "to_superop",
    "to_kraus",
    "truncate_kraus",
    "unitary_to_choi",
    "unitary_to_kraus_map",
    "unitary_to_pauli_liouville",
    "unitary_to_superop",
    # Distance metrics
    "fidelity",
    "process_fidelity",
    "to_choi",
    "unitary_entanglement_fidelity",
    "depolarizing_constant_to_average_fidelity",
    "average_fidelity_to_depolarizing_constant",
    "depolarizing_constant_to_process_fidelity",
    "process_fidelity_to_depolarizing_constant",
    "average_fidelity_to_process_fidelity",
    "process_fidelity_to_average_fidelity",
    "unitarity_to_stochastic_infidelity",
    "unitarity",
    "stochastic_infidelity",
    # Types
    "QuantumObject",
    "Choi",
    "SuperOp",
    "KrausMap",
    "PauliLiouville",
    "SuperOperator",
    "Unitary",
    "Observable",
    "Involution",
    "DensityMatrix",
    "StateVector",
    "State",
    "QuantumInstrument",
    "Operator",
    "Lindbladian",
    # Instrument fidelity functions
    "classification_fidelity",
    "instrument_fidelity",
    "non_demolition_fidelity",
    # State functions
    "zero_state_matrix",
    "zero_state_vector",
    "mixed_state_matrix",
    "tensor_density_matrices",
    "tensor_state_vectors",
    # Random functions
    "ginibre_matrix_complex",
    "random_density_matrix",
    "random_unitary",
    "random_choi",
    "random_state_vector",
    "random_operator",
    "random_observable",
    # Validation functions
    "validate",
    "is_hermitian",
    "is_hermicity_preserving",
    "is_unitary",
    "is_one_design",
    "is_two_design",
    "is_identity_matrix",
    "is_positive_semidefinite_matrix",
    "is_cptp",
    "is_completely_positive",
    "is_trace_preserving",
    # Promotion functions
    "embed",
    "permute",
    "promote",
    "promote_incoherent",
    "promote_state_vector_to_density_matrix",
    "promote_hilbert_space",
    "squeeze",
    # Operator basis functions
    "weyl_basis",
    "weyl_basis_labels",
    "hermitian_weyl_basis",
    "hermitian_weyl_basis_labels",
    "n_qudit_basis",
    "n_qudit_herm_basis",
    # Observables
    "bitstring_probability",
    "probabilities",
    # Power / evolution functions
    "power_choi",
    "power_kraus",
    "power_pauli_liouville",
    "power_superop",
    "power_unitary",
    "exp",
    "cis",
    "evolve",
    "unitary_to_hamiltonian",
    # Visualization
    "plot",
    # Submodules
    "gates",
    "states",
    "ensembles",
    "lindbladians",
]
